# Generated by Django 5.0.6 on 2024-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
