# Generated by Django 5.0.6 on 2024-05-13 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attendance', '0001_initial'),
        ('Schedule', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='id_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Schedule.schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Student.student'),
        ),
    ]
