# Generated by Django 5.0.6 on 2024-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_initial'),
        ('Schedule', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('id_schedule', 'id_student')},
        ),
    ]
