# Generated by Django 5.0.6 on 2024-05-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('list_attendance', 'can update list attendance'),)},
        ),
    ]
