# Generated by Django 5.0.6 on 2024-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='date_birth',
        ),
    ]
