# Generated by Django 5.0.6 on 2024-05-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.PositiveIntegerField(choices=[(2, 'Kurang Puas'), (1, 'Lumayan Puas'), (0, 'Sangat Puas')]),
        ),
    ]
