# Generated by Django 5.0.6 on 2024-05-13 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Class', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.PositiveIntegerField(choices=[(0, 'Woman'), (1, 'Man')])),
                ('age', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(5)])),
                ('number_phone', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=50)),
                ('distance', models.PositiveIntegerField()),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date_birth', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Class.class')),
            ],
        ),
    ]
